export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_PROGRESS = "LOAD_USER_PROGRESS";
export const LOAD_USER_FAILED = "LOAD_USER_FAILED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_PROGRESS = "SIGN_IN_PROGRESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
